apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
    spec:
      containers:
      - image: nginx:stable
        name: nginx-deployment
